Ch scaffold
kinyarwanda-net/ikinyarwanda-frontend pull request #1
Opened 2020-01-16 17:56 UTC by ceelogre

**What does this PR do?**

2020-01-17 09:29 UTC, kagaramag requested changes
Great work @ceelogre 
I can see Vue logo, can you change it and use **Ikinyarwanda** logo? Especially the **favicon**

2020-01-17 09:29 UTC, djallas commented on public/index.html
> +    <title>ikinyarwanda-frontend</title>
@ceelogre I think, for now, you can change this title to "**Ikinyarwanda**". Because end-users do not neet know if the web is "frontend"

2020-01-18 00:23 UTC, kagaramag reviewed
@ceelogre 
- Can you add **css** and **images** folders in assets too
- Remember to squash your commit

2020-01-24 13:52 UTC, nzuwera requested changes
npm test is not exiting, make it run once

2020-01-24 21:00 UTC, nzuwera approved these changes

2020-01-25 13:13 UTC, ceelogre commented
@djallas Please approve [this](https://github.com/kinyarwanda-net/ikinyarwanda-frontend/pull/1#pullrequestreview-344446390) RFC so we can proceed to merge.

2020-01-25 13:23 UTC, kagaramag approved these changes

2020-01-25 13:25 UTC, merged